import assert from 'node:assert/strict'
import test from 'node:test'
import React from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { QRCodeSVG } from 'qrcode.react'
import {
  FEC_SCHEMES,
  MAX_FILE_SIZE,
  OPTICAL_TRANSFER_CONFIG,
  PROTOCOL_VERSION,
  QR_PAYLOAD_PREFIX,
  SESSION_ID_BYTES,
  OpticalTransferProtocolError,
  bytesEqual,
  createLoopingFrameSchedule,
  createOpticalTransferCollector,
  createSessionId,
  crc32,
  decodeQrPayload,
  deserializePacket,
  detectImageMimeType,
  encodeQrPayload,
  parseQrPayload,
  prepareOpticalTransfer,
  sanitizeFilename,
  serializeDataPacket,
  serializeEndPacket,
  splitIntoChunks,
  validateImageBytes,
} from '../src/features/optical-transfer/protocol/index.js'

const IMAGE_SIGNATURES = {
  'image/png': [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a],
  'image/jpeg': [0xff, 0xd8, 0xff, 0xe0],
  'image/webp': [
    0x52,
    0x49,
    0x46,
    0x46,
    0x10,
    0,
    0,
    0,
    0x57,
    0x45,
    0x42,
    0x50,
  ],
  'image/gif': [0x47, 0x49, 0x46, 0x38, 0x39, 0x61],
}

function makeImageBytes(mimeType = 'image/png', size = 4_321) {
  const signature = IMAGE_SIGNATURES[mimeType]
  const bytes = new Uint8Array(Math.max(size, signature.length))
  let state = 0x12345678

  for (let index = 0; index < bytes.length; index += 1) {
    state = (Math.imul(state, 1_664_525) + 1_013_904_223) >>> 0
    bytes[index] = state >>> 24
  }
  bytes.set(signature)
  return bytes
}

function fixedSession(seed = 1) {
  return Uint8Array.from(
    { length: SESSION_ID_BYTES },
    (_value, index) => (seed + index * 17) & 0xff,
  )
}

function rewriteChecksum(packet) {
  const view = new DataView(packet.buffer, packet.byteOffset, packet.byteLength)
  view.setUint32(packet.length - 4, crc32(packet.subarray(0, -4)))
  return packet
}

function expectProtocolCode(code) {
  return (error) =>
    error instanceof OpticalTransferProtocolError && error.code === code
}

test('V1 defaults favor camera reliability and reserve FEC scheme zero', () => {
  assert.equal(PROTOCOL_VERSION, 1)
  assert.equal(OPTICAL_TRANSFER_CONFIG.chunkSize, 600)
  assert.equal(OPTICAL_TRANSFER_CONFIG.fps, 8)
  assert.equal(OPTICAL_TRANSFER_CONFIG.fecScheme, FEC_SCHEMES.NONE)
  assert.equal(OPTICAL_TRANSFER_CONFIG.qrErrorCorrection, 'M')
  assert.equal(crc32(new TextEncoder().encode('123456789')), 0xcbf43926)
})

test('session IDs contain 16 cryptographically generated bytes', () => {
  const first = createSessionId()
  const second = createSessionId()
  assert.equal(first.length, 16)
  assert.equal(second.length, 16)
  assert.equal(bytesEqual(first, second), false)
  assert.notDeepEqual(first, new Uint8Array(16))
})

test('supported image signatures are detected and must match declared MIME', () => {
  for (const mimeType of Object.keys(IMAGE_SIGNATURES)) {
    const bytes = makeImageBytes(mimeType, 128)
    assert.equal(detectImageMimeType(bytes), mimeType)
    assert.equal(validateImageBytes(bytes, mimeType), mimeType)
  }

  assert.throws(
    () => validateImageBytes(makeImageBytes('image/png'), 'image/jpeg'),
    expectProtocolCode('MIME_MAGIC_MISMATCH'),
  )
  assert.throws(
    () => validateImageBytes(new Uint8Array(100), 'image/png'),
    expectProtocolCode('INVALID_IMAGE_MAGIC'),
  )
})

test('filenames are normalized, path-safe, device-safe, and byte-bounded', () => {
  const sanitized = sanitizeFilename('../../folder\\\u0000evil?.png')
  assert.doesNotMatch(sanitized, /[\\/]/)
  assert.doesNotMatch(sanitized, /^\./)
  assert.equal(sanitized.includes('?'), false)
  assert.equal(sanitized.includes(String.fromCharCode(0)), false)
  assert.equal(sanitizeFilename('CON'), '_CON')
  assert.equal(sanitizeFilename('...'), 'image')
  assert.ok(new TextEncoder().encode(sanitizeFilename('📷'.repeat(100))).length <= 180)
})

test('raw bytes split into conservative chunks without text conversion', () => {
  const bytes = makeImageBytes('image/png', 1_401)
  const chunks = splitIntoChunks(bytes)
  assert.deepEqual(chunks.map((chunk) => chunk.length), [600, 600, 201])
  assert.deepEqual(
    Uint8Array.from(chunks.flatMap((chunk) => Array.from(chunk))),
    bytes,
  )
})

test('metadata and data packets have compact binary PMOT framing and CRC32', async () => {
  const bytes = makeImageBytes('image/png', 1_001)
  const transfer = await prepareOpticalTransfer({
    bytes,
    filename: 'unique-metadata-name.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const metadata = deserializePacket(transfer.metadataPacket)
  const data = deserializePacket(transfer.dataPackets[0])

  assert.equal(metadata.protocol, 'PMOT')
  assert.equal(metadata.type, 'metadata')
  assert.equal(metadata.metadata.filename, 'unique-metadata-name.png')
  assert.equal(metadata.metadata.size, bytes.length)
  assert.equal(metadata.metadata.totalChunks, 2)
  assert.equal(metadata.metadata.fecScheme, FEC_SCHEMES.NONE)
  assert.equal(data.type, 'data')
  assert.equal(data.chunkIndex, 0)
  assert.deepEqual(data.payload, bytes.subarray(0, 600))
  assert.equal(transfer.dataPackets[0].length, 24 + 6 + 600 + 4)

  const dataAsText = new TextDecoder().decode(transfer.dataPackets[0])
  assert.equal(dataAsText.includes('unique-metadata-name.png'), false)
})

test('Base64URL is applied only at the QR boundary and rejects malformed input', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes(),
    filename: 'image.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const encoded = encodeQrPayload(transfer.metadataPacket)
  assert.ok(encoded.startsWith(QR_PAYLOAD_PREFIX))
  assert.doesNotMatch(encoded.slice(QR_PAYLOAD_PREFIX.length), /[+/=]/)
  assert.deepEqual(decodeQrPayload(encoded), transfer.metadataPacket)
  assert.equal(parseQrPayload(encoded).type, 'metadata')

  assert.throws(() => decodeQrPayload('https://example.com/image.png'), expectProtocolCode('WRONG_PROTOCOL'))
  assert.throws(() => decodeQrPayload(`${QR_PAYLOAD_PREFIX}A`), expectProtocolCode('MALFORMED_QR_PAYLOAD'))
  assert.throws(() => decodeQrPayload(`${QR_PAYLOAD_PREFIX}***`), expectProtocolCode('MALFORMED_QR_PAYLOAD'))
  assert.throws(
    () => decodeQrPayload(`${QR_PAYLOAD_PREFIX}${'A'.repeat(3_000)}`),
    expectProtocolCode('QR_PAYLOAD_TOO_LARGE'),
  )
})

test('a default full data frame fits and renders with the bundled QR encoder', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes('image/png', 1_200),
    filename: 'qr-capacity.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const schedule = createLoopingFrameSchedule(transfer)
  const dataFrameIndex = Array.from(
    { length: schedule.framesPerCycle },
    (_value, index) => index,
  ).find((index) => schedule.getDescriptor(index).type === 'data')
  const payload = schedule.getQrPayload(dataFrameIndex)
  let markup = ''

  assert.doesNotThrow(() => {
    markup = renderToStaticMarkup(
      React.createElement(QRCodeSVG, {
        value: payload,
        level: OPTICAL_TRANSFER_CONFIG.qrErrorCorrection,
        marginSize: 3,
        size: 640,
      }),
    )
  })
  assert.ok(payload.startsWith(QR_PAYLOAD_PREFIX))
  assert.ok(markup.startsWith('<svg'))
})

test('looping schedule repeats metadata periodically and then repeats the cycle', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes('image/png', 6_001),
    filename: 'schedule.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const schedule = createLoopingFrameSchedule(transfer, {
    metadataInterval: 4,
  })
  const descriptors = Array.from(
    { length: schedule.framesPerCycle },
    (_value, index) => schedule.getDescriptor(index),
  )
  const dataIndexes = descriptors
    .filter(({ type }) => type === 'data')
    .map(({ chunkIndex }) => chunkIndex)

  assert.deepEqual(
    dataIndexes,
    Array.from({ length: transfer.metadata.totalChunks }, (_value, index) => index),
  )
  assert.equal(
    descriptors.filter(({ type }) => type === 'metadata').length,
    Math.ceil(transfer.metadata.totalChunks / 4),
  )
  assert.equal(descriptors.at(-1).type, 'end')
  assert.equal(schedule.getQrPayload(0), schedule.getQrPayload(schedule.framesPerCycle))
  assert.equal(schedule.fps, 8)
})

test('compact END packets delimit cycles but never fake receiver completion', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes('image/png', 1_201),
    filename: 'end-frame.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const parsedEnd = deserializePacket(transfer.endPacket)
  assert.equal(parsedEnd.type, 'end')
  assert.equal(parsedEnd.totalChunks, transfer.metadata.totalChunks)
  assert.equal(transfer.endPacket.length, 24 + 4 + 4)

  const collector = createOpticalTransferCollector()
  assert.equal(collector.ingestPacket(transfer.endPacket).reason, 'metadata-required')
  collector.ingestPacket(transfer.metadataPacket)
  const firstEnd = collector.ingestPacket(transfer.endPacket)
  assert.equal(firstEnd.accepted, true)
  assert.equal(firstEnd.duplicate, false)
  assert.equal(firstEnd.ready, false)
  assert.equal(firstEnd.snapshot.endSeen, true)
  assert.equal(collector.ingestPacket(transfer.endPacket).duplicate, true)

  const mismatchedEnd = serializeEndPacket({
    sessionId: transfer.sessionId,
    totalChunks: transfer.metadata.totalChunks + 1,
  })
  assert.throws(
    () => collector.ingestPacket(mismatchedEnd),
    expectProtocolCode('INVALID_TOTAL_CHUNKS'),
  )
  assert.equal(collector.ready, false)
})

test('collector deduplicates and reconstructs out-of-order chunks byte exactly', async () => {
  const original = makeImageBytes('image/png', 14_321)
  const transfer = await prepareOpticalTransfer({
    bytes: original,
    filename: 'out-of-order.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const collector = createOpticalTransferCollector()
  collector.ingestQrFrame(encodeQrPayload(transfer.metadataPacket))

  const frames = transfer.dataPackets.map(encodeQrPayload).reverse()
  for (const frame of frames) {
    collector.ingestQrFrame(frame)
  }
  const duplicate = collector.ingestQrFrame(frames[0])

  assert.equal(duplicate.duplicate, true)
  assert.equal(collector.getSnapshot().duplicateCount, 1)
  assert.equal(collector.getSnapshot().progress, 1)
  assert.equal(collector.getSnapshot().ready, true)
  const result = await collector.assembleAndVerify()
  assert.deepEqual(result.bytes, original)
  assert.equal(result.sha256Hex, transfer.metadata.sha256Hex)
  assert.equal(collector.getSnapshot().complete, true)
})

test('collector refuses reconstruction while chunks are missing', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes('image/png', 2_000),
    filename: 'missing.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const collector = createOpticalTransferCollector()
  collector.ingestPacket(transfer.metadataPacket)
  collector.ingestPacket(transfer.dataPackets[0])
  await assert.rejects(
    collector.assembleAndVerify(),
    expectProtocolCode('MISSING_CHUNKS'),
  )
})

test('data seen before periodic metadata is ignored instead of binding a session', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes(),
    filename: 'mid-cycle.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const collector = createOpticalTransferCollector()
  const ignored = collector.ingestPacket(transfer.dataPackets[0])
  assert.equal(ignored.accepted, false)
  assert.equal(ignored.reason, 'metadata-required')
  assert.equal(collector.getSnapshot().sessionId, null)

  collector.ingestPacket(transfer.metadataPacket)
  for (const packet of transfer.dataPackets) {
    collector.ingestPacket(packet)
  }
  assert.equal(collector.getSnapshot().ready, true)
})

test('wrong-session frames cannot contaminate an active collector', async () => {
  const [first, second] = await Promise.all([
    prepareOpticalTransfer({
      bytes: makeImageBytes('image/png', 900),
      filename: 'first.png',
      mimeType: 'image/png',
      sessionId: fixedSession(3),
    }),
    prepareOpticalTransfer({
      bytes: makeImageBytes('image/png', 900),
      filename: 'second.png',
      mimeType: 'image/png',
      sessionId: fixedSession(9),
    }),
  ])
  const collector = createOpticalTransferCollector()
  collector.ingestPacket(first.metadataPacket)
  assert.equal(collector.ingestPacket(second.metadataPacket).reason, 'session-mismatch')
  assert.equal(collector.ingestPacket(second.dataPackets[0]).reason, 'session-mismatch')
  assert.equal(collector.getSnapshot().metadata.filename, 'first.png')
  assert.equal(collector.getSnapshot().uniqueChunks, 0)

  const pinned = createOpticalTransferCollector({
    expectedSessionId: first.sessionId,
  })
  assert.equal(pinned.ingestPacket(second.metadataPacket).reason, 'session-mismatch')
})

test('CRC corruption and unsupported versions are rejected', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes(),
    filename: 'corruption.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const corrupted = transfer.dataPackets[0].slice()
  corrupted[40] ^= 0xff
  assert.throws(() => deserializePacket(corrupted), expectProtocolCode('CRC_MISMATCH'))

  const futureVersion = transfer.metadataPacket.slice()
  futureVersion[4] = 2
  rewriteChecksum(futureVersion)
  assert.throws(
    () => deserializePacket(futureVersion),
    expectProtocolCode('UNSUPPORTED_VERSION'),
  )
})

test('collector validates chunk indexes, lengths, conflicts, and repeated metadata', async () => {
  const original = makeImageBytes('image/png', 1_201)
  const transfer = await prepareOpticalTransfer({
    bytes: original,
    filename: 'bounds.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const collector = createOpticalTransferCollector()
  collector.ingestPacket(transfer.metadataPacket)

  const badIndex = serializeDataPacket({
    sessionId: transfer.sessionId,
    chunkIndex: transfer.metadata.totalChunks,
    payload: original.subarray(0, 600),
  })
  assert.throws(() => collector.ingestPacket(badIndex), expectProtocolCode('INVALID_CHUNK_INDEX'))

  const shortChunk = serializeDataPacket({
    sessionId: transfer.sessionId,
    chunkIndex: 0,
    payload: original.subarray(0, 599),
  })
  assert.throws(() => collector.ingestPacket(shortChunk), expectProtocolCode('INVALID_CHUNK_LENGTH'))

  collector.ingestPacket(transfer.dataPackets[0])
  const conflictingChunk = serializeDataPacket({
    sessionId: transfer.sessionId,
    chunkIndex: 0,
    payload: Uint8Array.from(original.subarray(0, 600), (byte) => byte ^ 1),
  })
  assert.throws(() => collector.ingestPacket(conflictingChunk), expectProtocolCode('CHUNK_CONFLICT'))

  const otherMetadata = await prepareOpticalTransfer({
    bytes: original,
    filename: 'different-name.png',
    mimeType: 'image/png',
    sessionId: transfer.sessionId,
  })
  assert.throws(
    () => collector.ingestPacket(otherMetadata.metadataPacket),
    expectProtocolCode('METADATA_CONFLICT'),
  )
})

test('malicious huge file metadata is rejected before allocating chunk storage', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes(),
    filename: 'huge.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })
  const malicious = transfer.metadataPacket.slice()
  const view = new DataView(malicious.buffer)
  view.setUint32(24, MAX_FILE_SIZE + 1)
  rewriteChecksum(malicious)
  assert.throws(() => deserializePacket(malicious), expectProtocolCode('FILE_TOO_LARGE'))
})

test('final verification rejects altered SHA-256 metadata and MIME declarations', async () => {
  const transfer = await prepareOpticalTransfer({
    bytes: makeImageBytes('image/png', 1_001),
    filename: 'integrity.png',
    mimeType: 'image/png',
    sessionId: fixedSession(),
  })

  const badHashMetadata = transfer.metadataPacket.slice()
  badHashMetadata[37] ^= 0xff
  rewriteChecksum(badHashMetadata)
  const hashCollector = createOpticalTransferCollector()
  hashCollector.ingestPacket(badHashMetadata)
  for (const packet of transfer.dataPackets) {
    hashCollector.ingestPacket(packet)
  }
  await assert.rejects(
    hashCollector.assembleAndVerify(),
    expectProtocolCode('SHA256_MISMATCH'),
  )

  const jpegDeclaredMetadata = transfer.metadataPacket.slice()
  jpegDeclaredMetadata[34] = 2
  rewriteChecksum(jpegDeclaredMetadata)
  const mimeCollector = createOpticalTransferCollector()
  mimeCollector.ingestPacket(jpegDeclaredMetadata)
  for (const packet of transfer.dataPackets) {
    mimeCollector.ingestPacket(packet)
  }
  await assert.rejects(
    mimeCollector.assembleAndVerify(),
    expectProtocolCode('MIME_MAGIC_MISMATCH'),
  )
})

function createLossGenerator(seed) {
  let state = seed >>> 0
  return () => {
    state = (Math.imul(state, 1_664_525) + 1_013_904_223) >>> 0
    return state / 0x1_0000_0000
  }
}

for (const dropRate of [0.1, 0.2]) {
  test(`${dropRate * 100}% frame loss, duplicates, out-of-order scans, and a mid-cycle start recover exactly`, async () => {
    const original = makeImageBytes('image/png', 48_217)
    const transfer = await prepareOpticalTransfer({
      bytes: original,
      filename: `loss-${dropRate}.png`,
      mimeType: 'image/png',
      sessionId: fixedSession(Math.round(dropRate * 100)),
    })
    const schedule = createLoopingFrameSchedule(transfer, {
      metadataInterval: 8,
    })
    const collector = createOpticalTransferCollector()
    const random = createLossGenerator(0xabc000 + dropRate * 100)
    const startFrame = Math.floor(schedule.framesPerCycle / 2)
    const scanWindow = []
    const maximumFrames = schedule.framesPerCycle * 12

    for (let offset = 0; offset < maximumFrames && !collector.ready; offset += 1) {
      const frame = schedule.getQrPayload(startFrame + offset)
      if (random() >= dropRate) {
        scanWindow.push(frame)
      }

      if (scanWindow.length === 7 || offset === maximumFrames - 1) {
        scanWindow.reverse()
        for (const scannedFrame of scanWindow) {
          const result = collector.ingestQrFrame(scannedFrame)
          if (result.accepted && random() < 0.15) {
            collector.ingestQrFrame(scannedFrame)
          }
        }
        scanWindow.length = 0
      }
    }

    assert.equal(collector.ready, true)
    assert.ok(collector.duplicateCount > 0)
    const result = await collector.assembleAndVerify()
    assert.deepEqual(result.bytes, original)
  })
}
